apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        # Docker Desktop kullandığınız için lokalde üretilen image doğrudan erişilebilir
        image: catalog_service:latest          # GHCR etiketiniz varsa buraya yazın
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
  - port: 80          # iç servis portu
    targetPort: 8001  # pod’daki containerPort
